apiVersion: v1
kind: Service
metadata:
  name: {{ template "neo4j.fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "neo4j.name" . }}
    component: core
spec:
  clusterIP: None
  ports:
    - name: http
      port: {{ .Values.service.http.port }}
      targetPort: http
    - name: bolt
      port: {{ .Values.service.bolt.port }}
      targetPort: bolt
  selector:
    app: {{ template "neo4j.name" . }}
    release: {{ .Release.Name | quote }}
    component: core
